context:
  name: csp-bot
  version: "1.0.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
    url: https://pypi.org/packages/source/c/csp-bot/csp_bot-${{ version }}.tar.gz
    sha256: 71fb4f5da144d5a7e6059876226e4ddb7e6a4cc6b570b348bbb473d00278f7cf

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - beautifulsoup4
    - ccflow
    - croniter
    - csp
    - csp-gateway
    - csp-adapter-discord
    - csp-adapter-slack
    - csp-adapter-symphony
    - dateparser
    - hydra-core
    - pandas
    - pydantic >=2

tests:
  - python:
      imports:
        - csp_bot
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Reactive chat bot framework
  homepage: https://github.com/Point72/csp-bot/wiki
  repository: https://github.com/Point72/csp-bot

extra:
  recipe-maintainers:
    - timkpaine
